export const items = [
    {
      key: '1',
      artist: 4,
      image: 'https://assets.codepen.io/3685267/nft-dashboard-art-0.jpg',
      price: '3.8',
      title: 'People Abstract Painting',
      timeLeft: 84670923,
    },
    {
      key: '2',
      artist: 2,
      image: 'https://assets.codepen.io/3685267/nft-dashboard-art-1.jpg',
      price: '2.5',
      title: 'Abstract Art Painting',
      timeLeft: 12873491,
    },
    {
      key: '3',
      artist: 0,
      image: 'https://assets.codepen.io/3685267/nft-dashboard-art-2.jpg',
      price: '9.0',
      title: 'Purple Liquid Painting',
      timeLeft: 84720185,
    },
    {
      key: '4',
      artist: 3,
      image: 'https://assets.codepen.io/3685267/nft-dashboard-art-3.jpg',
      price: '16.5',
      title: 'Generative Art',
      timeLeft: 43826185,
    },
    {
      key: '5',
      artist: 2,
      image: 'https://assets.codepen.io/3685267/nft-dashboard-art-4.jpg',
      price: '4.0',
      title: 'Liquid Base Painting',
      timeLeft: 134627,
    },
    {
      key: '6',
      artist: 1,
      image: 'https://assets.codepen.io/3685267/nft-dashboard-art-5.jpg',
      price: '1.3',
      title: 'Colorful Wind Painting',
      timeLeft: 12008745,
    },
  ];